apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-datos-mysql-env
  namespace: {{ .Values.namespace}}
data:
  MYSQL_DATABASE: {{.Values.bbdd}}
  MYSQL_PASSWORD: {{.Values.pass}}
  MYSQL_ROOT_PASSWORD: {{.Values.root}}
  MYSQL_USER: {{.Values.usudb}}

